import {auth} from "@/auth";
import {ModalProvider} from "@/components/modal-provider";
import {Provider} from "@/components/providers";
import {SiteFooter} from "@/components/site-footer";
import {SiteHeader} from "@/components/site-header";
import {TailwindIndicator} from "@/components/tailwind-indicator";
import {Toaster} from "@/components/ui/toaster";
import {fontSans} from "@/lib/fonts";
import {cn} from "@/lib/utils";
import "@/styles/globals.css";
import type {Metadata, Viewport} from "next";
import {SessionProvider} from "next-auth/react";

export const metadata: Metadata = {
  title: {
    default: "Task Manager",
    template: "Task Manager | %s",
  },
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    {media: "(prefers-color-scheme: light)", color: "white"},
    {media: "(prefers-color-scheme: dark)", color: "black"},
  ],
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({children}: Readonly<RootLayoutProps>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.className
          )}>
          <Provider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <Toaster />
            <TailwindIndicator />
            <ModalProvider>
              <div className="relative flex min-h-screen flex-col bg-background">
                <SiteHeader />
                <main className="flex flex-1 items-center justify-center overflow-auto">
                  {children}
                </main>
                <SiteFooter />
              </div>
            </ModalProvider>
          </Provider>
        </body>
      </html>
    </SessionProvider>
  );
}
